/* HERE YOU PUT THE ACTIONS CONSTANTS */

export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const USER_EDIT = "USER_EDIT";

export const INTEGRATION_ADD = "INTEGRATION_ADD";
export const SELECT_INTEGRATION = "SELECT_INTEGRATION";
export const SELECT_STORE = "SELECT_STORE";
export const ERROR_SELECTING_STORE = "ERROR_SELECTING_STORE";

export const ADD_RAPPI_ITEMS = "ADD_RAPPI_ITEMS";

export const LOADING = "LOADING";
export const ERROR = "ERROR";

export const ADD_ITEMS = "ADD_ITEMS";
export const UPDATE_ITEMS = "UPDATE_ITEMS";
export const DELETE_ITEMS = "DELETE_ITEMS";
export const RESET_STORE = "RESET_STORE";

export const SELECT_COUNTRY = "SELECT_COUNTRY";

export const UPDATE_DRAFTS = "UPDATE_DRAFTS";
export const SET_ACTIVE_DRAFT = "SET_ACTIVE_DRAFT";
export const UPDATE_MAPPINGS = "UPDATE_MAPPINGS";

export const LOAD_RESTAURANT_MENU_FILE = "LOAD_RESTAURANT_MENU_FILE";
export const SELECT_MAPPING_STORE_TYPE = "SELECT_MAPPING_STORE_TYPE";
export const SELECT_BASE_MAPPING = "SELECT_BASE_MAPPING";
export const SELECT_BASE_MAPPING_TYPE = "SELECT_BASE_MAPPING_TYPE";
export const SELECT_MAPPING_STORE = "SELECT_MAPPING_STORE";
export const SELECT_MAPPING_INTEGRATION = "SELECT_MAPPING_INTEGRATION";
